### ISSUE TITLE
Test fail for 3.7.0

### ISSUE THREAD

**Issue by roncewind** [Senzing/serve-grpc#186]
**Describe the bug**
The unit test `ExampleG2EngineServer_GetRecord` fails when run against Senzing 3.7.0

**To Reproduce**

`make test` with senzing 3.7.0

**Expected behavior**
The expectation is that unit tests won't fail.

The issue is that we're validating against a static JSON string.  It seems that the output of the `GetRecord` method is in flux.  We're expecting to get two fields `DSRC_ACTION` and `ENTITY_TYPE` which are not returned for 3.7.0.  It might make more sense for us to validate the response by parsing what is returned and looking for specific necessary fields.  I'm guessing that order also matters in the current test?  If so, parsing and checking particular fields would eliminate any issues with return order.

**Comment by docktermj** [comment]
Until a release of Senzing comes out with the Go Support, the code in `serve-grpc` won't work.  As a temporary work-around, pull the version of Senzing from "staging".
